Repository wazo-platform/wazo-dird, pull requests merged in 2021-04, with the labels that each got.

#101 test: update deprecated acls property
  integration_tests/suite/test_graphql.py
Labels: auto-merge, mergeit

#103 office/google: do not use logger.error in normal situations
  wazo_dird/plugins/google_backend/services.py
  wazo_dird/plugins/office365_backend/services.py
Labels: auto-merge

#102 graphql: avoid failing when a column is missing from a source
  integration_tests/assets/docker-compose.all_routes.override.yml
  integration_tests/assets/tmp/data/asset.all_routes.test_no_email.csv
  integration_tests/suite/helpers/config.py
  integration_tests/suite/test_graphql.py
  wazo_dird/plugins/graphql/resolver.py
Labels: mergeit

#104 test: use explicit ipv4 addr to connect docker
  integration_tests/assets/ssl/generic/openssl.cfg
  integration_tests/assets/ssl/generic/server.crt
  integration_tests/assets/ssl/generic/server.key
  integration_tests/suite/helpers/base.py
  integration_tests/suite/helpers/constants.py
  integration_tests/suite/helpers/fixtures/http.py
  integration_tests/suite/test_auto_create.py
  integration_tests/suite/test_bus.py
  integration_tests/suite/test_conference_backend.py
  integration_tests/suite/test_csv_ws_backend.py
  integration_tests/suite/test_documentation.py
  integration_tests/suite/test_favorites.py
  integration_tests/suite/test_google_contacts.py
  integration_tests/suite/test_graphql.py
  integration_tests/suite/test_ldap_backend.py
  integration_tests/suite/test_office365_backend.py
  integration_tests/suite/test_office365_contacts.py
  integration_tests/suite/test_personal.py
  integration_tests/suite/test_wazo_user_backend.py
Labels: auto-merge, mergeit
